template:
  - sensor:
      - name: "Lake Hood Zone - Radius"
        unique_id: "lake_hood_zone_radius"
        state: "Zone - Radius"
        icon: "mdi:radius-outline"
        attributes:
          p_1: "[-149.9713961575617, 61.18193701948563]"
          radius : 500
          units: "Feet"
          is_closed: true
      - name: "Lake Hood Zone - polygon"
        unique_id: "lake_hood_zone_polygon"
        state: "Zone - Polygon"
        icon: "mdi:shape-polygon-plus"
        attributes:
          p_1: "[-149.9714801762212, 61.18220193377709]"
          p_2: "[-149.9716773748038, 61.18195478028175]"
          p_3: "[-149.9716855038654, 61.18188228574225]"
          p_4: "[-149.9713782633992, 61.1818286392424]"
          p_5: "[-149.9713094444549, 61.18183260821363]"
          p_6: "[-149.9710822363566, 61.18213539980892]"
          p_7: "[-149.9714801762212, 61.18220193377709]"
          is_closed: true
      - name: "Ted Stevens Airport Zone"
        unique_id: "ted_stevens_airport_zone"
        state: "Zone - Polygon"
        icon: "mdi:shape-polygon-plus"
        attributes:
          p_1:  "[-150.0473937469993, 61.16639584745547]"
          p_2:  "[-149.9701612614392, 61.16683672889118]"
          p_3:  "[-149.9637548431457, 61.16877164284922]"
          p_4:  "[-149.9447116679241, 61.16894553112301]"
          p_5:  "[-149.9447863575852, 61.17309363198385]"
          p_6:  "[-149.9555154105149, 61.1740687471149]"
          p_7:  "[-149.9608586822121, 61.17549760206925]"
          p_8:  "[-149.9723421163276, 61.17559275349169]"
          p_9:  "[-149.978655499852, 61.17531646806917]"
          p_10: "[-149.980476060952, 61.17651722573332]"
          p_11: "[-149.9835351239655, 61.17997611919068]"
          p_12: "[-149.9907121439279, 61.18029998613355]"
          p_13: "[-149.9968322245572, 61.17933193641611]"
          p_14: "[-149.9966409766171, 61.17937803762539]"
          p_15: "[-150.0098128356535, 61.20044844928754]"
          p_16: "[-150.0129690588434, 61.20031547767132]"
          p_17: "[-150.0143042251923, 61.20104914493516]"
          p_18: "[-150.0163106622618, 61.20049795166577]"
          p_19: "[-150.0143030905012, 61.19566828277897]"
          p_20: "[-150.0166784006209, 61.19492508812836]"
          p_21: "[-150.0052314089938, 61.17316463507193]"
          p_22: "[-150.0068533857222, 61.17256673212079]"
          p_23: "[-150.0437459736553, 61.17234923467412]"
          p_24: "[-150.0445215442077, 61.16982928026749]"
          p_25: "[-150.0475239221786, 61.16880426257448]"
          p_26: "[-150.0473937469993, 61.16639584745547]"
          is_closed: true
      - name: "Coastal Trail Zone North"
        unique_id: "coastal_trail_zone_north"
        state: "Zone - Polyline"
        icon: "mdi:road-variant"
        attributes:
          p_1: "[-149.9539609749104, 61.20151667810528]"
          p_2: "[-149.9524397617161, 61.20190165433212]"
          p_3: "[-149.9517677915486, 61.20210080555632]"
          p_4: "[-149.9513452980941, 61.20222801994535]"
          p_5: "[-149.9508917255797, 61.2022940278467]"
          p_6: "[-149.9505117425726, 61.20232962162248]"
          p_7: "[-149.9501315282977, 61.20236027043111]"
          p_8: "[-149.9496983116343, 61.20247771620955]"
          p_9: "[-149.9492135101159, 61.20263033614517]"
          p_10: "[-149.9486666704158, 61.20280288159094]"
          p_11: "[-149.9482886868802, 61.20289913740406]"
          p_12: "[-149.9477845376093, 61.20301048487791]"
          p_13: "[-149.9474373478848, 61.20306113006433]"
          p_14: "[-149.9468910971998, 61.20310665988666]"
          p_15: "[-149.9464275684273, 61.20322826601892]"
          p_16: "[-149.9461616735793, 61.20338064967257]"
          p_17: "[-149.9459873428204, 61.2035947966143]"
          p_18: "[-149.9458143138713, 61.20380413458231]"
          p_19: "[-149.9455478182649, 61.20393195969158]"
          p_20: "[-149.9452285602392, 61.2040089165036]"
          p_21: "[-149.9447020369026, 61.20412037127868]"
          p_22: "[-149.9439013380545, 61.20427243261361]"
          p_23: "[-149.9436153753541, 61.20434384228545]"
          p_24: "[-149.9432429371681, 61.20438010027114]"
          p_25: "[-149.9425467735234, 61.20445104569035]"
          p_26: "[-149.9419536042133, 61.20455312063001]"
          p_27: "[-149.9413981510741, 61.20468437374552]"
          p_28: "[-149.9410746085184, 61.20475978807677]"
          p_29: "[-149.9406862226901, 61.20484992067068]"
          p_30: "[-149.9402960361122, 61.20487963008562]"
          p_31: "[-149.9400323244352, 61.20487947342757]"
          p_32: "[-149.9397999173415, 61.20493558552973]"
          p_33: "[-149.939599576574, 61.20503705343293]"
          p_34: "[-149.9393360961914, 61.20511807828235]"
          p_35: "[-149.9389884364675, 61.20518375401535]"
          p_36: "[-149.9386631728752, 61.20522332374866]"
          p_37: "[-149.9383786337285, 61.20527910295679]"
          p_38: "[-149.9380626131868, 61.20537542384613]"
          p_39: "[-149.93767487446, 61.20557776370131]"
          p_40: "[-149.9372833386974, 61.20565944912416]"
          p_41: "[-149.9368159112424, 61.2057368913669]"
          p_42: "[-149.9362033652506, 61.20577504005367]"
          p_43: "[-149.9356838905174, 61.20585926024347]"
          p_44: "[-149.9352638297606, 61.20588870881267]"
          p_45: "[-149.9347864157872, 61.20592494711376]"
          p_46: "[-149.9343021057358, 61.20585804900985]"
          p_47: "[-149.9338365183685, 61.20585817272688]"
          p_48: "[-149.9336268725695, 61.20584238138815]"
          p_49: "[-149.9334993133796, 61.20579676315727]"
          p_50: "[-149.9333408554768, 61.20567457691674]"
          p_51: "[-149.9331295340383, 61.20560838029854]"
          p_52: "[-149.9329736796233, 61.20560275111174]"
          p_53: "[-149.9321722283592, 61.2057563367095]"
          p_54: "[-149.9319060239918, 61.20585697976015]"
          p_55: "[-149.9317277222335, 61.20601618866664]"
          p_56: "[-149.9316271106012, 61.20615176914379]"
          p_57: "[-149.9314043034615, 61.20621844704733]"
          p_58: "[-149.9310612964869, 61.20625579826053]"
          p_59: "[-149.9305287312887, 61.20626321295]"
          p_60: "[-149.9302390654221, 61.20630180830682]"
          p_61: "[-149.929826830541, 61.20634616186277]"
          p_62: "[-149.9282204099142, 61.20664155897853]"
          p_63: "[-149.9280255987224, 61.20666754469864]"
          p_64: "[-149.9278747623106, 61.20666115596653]"
          p_65: "[-149.9276285526282, 61.20661594952762]"
          p_66: "[-149.9271855173401, 61.20646782278646]"
          p_67: "[-149.9269195648565, 61.20638429290296]"
          p_68: "[-149.9264855911264, 61.20629143558794]"
          p_69: "[-149.9259173039681, 61.20620499783948]"
          p_70: "[-149.9254652463599, 61.20618973185779]"
          p_71: "[-149.9248918446568, 61.20620091333532]"
          p_72: "[-149.9245341178741, 61.20621702421371]"
          p_73: "[-149.9243968223949, 61.20627027935887]"
          p_74: "[-149.9242375706102, 61.20635843727395]"
          p_75: "[-149.924204540177, 61.2064398140874]"
          p_76: "[-149.924186778953, 61.20752898211529]"
          p_77: "[-149.9241706516567, 61.20791568581915]"
          p_78: "[-149.9240484793384, 61.20804983651316]"
          p_79: "[-149.9238098166641, 61.20825752348609]"
          p_80: "[-149.9232535021119, 61.20854954160193]"
          p_81: "[-149.9231683968601, 61.20863929151027]"
          p_82: "[-149.9227461619936, 61.20880744497545]"
          p_83: "[-149.9227040012858, 61.20888313528973]"
          p_84: "[-149.9226967735128, 61.20912321186191]"
          p_85: "[-149.9227952925782, 61.20929081329181]"
          p_86: "[-149.9230360310049, 61.20946067713653]"
          p_87: "[-149.9230878578316, 61.20964570189948]"
          p_88: "[-149.9231246970097, 61.20977509807503]"
          p_89: "[-149.9231048859553, 61.20993899382567]"
          p_90: "[-149.9230208899204, 61.21009662127252]"
          p_91: "[-149.9227765039013, 61.21026067096164]"
          p_92: "[-149.9224263145601, 61.21046929700569]"
          p_93: "[-149.9216457695383, 61.21092930965128]"
          p_94: "[-149.921252305388, 61.21112312609062]"
          p_95: "[-149.9209673138439, 61.21116169660358]"
          p_96: "[-149.9206884599999, 61.21115961695563]"
          p_97: "[-149.9204813805476, 61.21122044151902]"
          p_98: "[-149.9202543216312, 61.21136205738207]"
          p_99: "[-149.9197183142779, 61.2117096821879]"
          p_100: "[-149.9191531883108, 61.21193992969216]"
          p_101: "[-149.9186867008217, 61.21211729912434]"
          p_102: "[-149.9183303802687, 61.21232377883515]"
          p_103: "[-149.9179083477892, 61.21252668264365]"
          p_104: "[-149.9175022281078, 61.21268694314583]"
          p_105: "[-149.9171937496811, 61.21299221119285]"
          p_106: "[-149.9169651596755, 61.21320417338985]"
          p_107: "[-149.9163079858033, 61.21352169245641]"
          p_108: "[-149.9146030430604, 61.21436516818886]"
          p_109: "[-149.9136315641746, 61.21487983077925]"
          p_110: "[-149.9128608065549, 61.21527875940657]"
          p_111: "[-149.912463900658, 61.21542111242492]"
          p_112: "[-149.9119261769189, 61.21559616175389]"
          p_113: "[-149.9116589478878, 61.21573153851212]"
          p_114: "[-149.9113199258009, 61.21595164192669]"
          p_115: "[-149.910950901357, 61.21624864148737]"
          p_116: "[-149.9104404823441, 61.21655766069205]"
          p_117: "[-149.9098754021566, 61.216871716652]"
          p_118: "[-149.9094178758748, 61.21716792509775]"
          p_119: "[-149.9089280124852, 61.21745903098977]"
          p_120: "[-149.9087811946505, 61.21763939789131]"
          p_121: "[-149.9084800322486, 61.2177746097062]"
          p_122: "[-149.9081679072053, 61.21781256013613]"
          p_123: "[-149.9077530130007, 61.21785516693915]"
          p_124: "[-149.9073715606474, 61.21787155611902]"
          p_125: "[-149.9070747387725, 61.21792624650261]"
          p_126: "[-149.9069125151784, 61.2180453211299]"
          p_127: "[-149.9067844367047, 61.21822765570719]"
          p_128: "[-149.9064142047944, 61.21847556463106]"
          p_129: "[-149.9057819718161, 61.21886547123981]"
          p_130: "[-149.9047361547991, 61.21949476149113]"
          p_131: "[-149.9036094259602, 61.22015928139856]"
          is_closed: false
          offset: 30
          units: "Feet"
